#!/bin/sh

set -e

echo '+cargo test --all-features'
cargo test --all-features
echo '+cargo clippy --all -- -D warnings'
cargo clippy --all-features -- -D warnings
echo '+cargo fmt --all -- --check'
cargo fmt --all -- --check
echo '+leptosfmt --check .'
leptosfmt --check .