#![recursion_limit = "256"]
pub mod about_us;
pub mod airdrop;
pub mod consts;
pub mod err;
pub mod faq;
pub mod hon;
pub mod leaderboard;
pub mod logout;
pub mod menu;
pub mod notifs;
pub mod post_view;
pub mod privacy;
pub mod profile;
pub mod refer_earn;
pub mod root;
pub mod scrolling_post_view;
pub mod settings;
pub mod terms;
pub mod terms_android;
pub mod terms_ios;
pub mod token;
pub mod upload;
pub mod view_profile_redirect;
pub mod wallet;
#[cfg(any(feature = "oauth-ssr", feature = "oauth-hydrate"))]
pub mod yral_auth_redirect;

pub mod pumpdump;
